### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by laautarolopez** [KylePDockery/BankingApp#1]
Hi! I would like to collaborate in this project.
I saw some problems. What would be the idea in general?

**Comment by KylePDockery** [comment]
Hi and thanks for your interest.
I would appreciate any feedback/contributions you would be interested to make.
The general idea is basically that I'm trying to get more actively involved in Java development and this was a basic project idea that I could learn from and grow with.

Being a student project, I just hope it is worth your time whatever you contribute. Thanks!

**Comment by laautarolopez** [comment]
I'm interested in contributing.
I would like to know if you could list certain issues to take some and be able to help.

**Comment by KylePDockery** [comment]
I've created a few issues of ideas I've had. I'd also love to hear any suggestions you have for additions. Cheers!
